config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :products
      resources :productos
      resources :verificates
    end
  end
end

app/models/verificate.rb
class Verificate < ActiveRecord::Base
end

app/controllers/api/v1/verificates_controller.rb
class Api::V1::VerificatesController < ApplicationController
  
  skip_before_action :verify_authenticity_token
  
  # GET /products
  def index
    productos = Producto.order("created_at DESC")
    render json: {status: 'Exitoso', message: 'Productos cargados', data: productos}, status: :ok
  end
  
  # POST /products
  # POST /products.json
  def create
    producto = Producto.new(producto_params)
    
    if Producto.exists?(id_producto: params[:id_producto])
        render json: {status: 'Error', message: 'No debe tener el mismo id'}, status: :unprocessable_entity
    else
        render json: {status: 'Excelente', message: 'El id es unico'}, status: :ok
    end
  end
  
  private

    def producto_params
      params.permit(:id_producto, :descripcion_producto, :precio_producto, :stockCrear)
    end
    
end

app/controllers/verificates_controller.rb
class VerificatesController < ApplicationController
  before_action :set_verificate, only: [:show, :edit, :update, :destroy]

  # GET /verificates
  # GET /verificates.json
  def index
    @verificates = Verificate.all
  end

  # GET /verificates/1
  # GET /verificates/1.json
  def show
  end

  # GET /verificates/new
  def new
    @verificate = Verificate.new
  end

  # GET /verificates/1/edit
  def edit
  end

  # POST /verificates
  # POST /verificates.json
  def create
    @verificate = Verificate.new(verificate_params)

    respond_to do |format|
      if @verificate.save
        format.html { redirect_to @verificate, notice: 'Verificate was successfully created.' }
        format.json { render :show, status: :created, location: @verificate }
      else
        format.html { render :new }
        format.json { render json: @verificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verificates/1
  # PATCH/PUT /verificates/1.json
  def update
    respond_to do |format|
      if @verificate.update(verificate_params)
        format.html { redirect_to @verificate, notice: 'Verificate was successfully updated.' }
        format.json { render :show, status: :ok, location: @verificate }
      else
        format.html { render :edit }
        format.json { render json: @verificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verificates/1
  # DELETE /verificates/1.json
  def destroy
    @verificate.destroy
    respond_to do |format|
      format.html { redirect_to verificates_url, notice: 'Verificate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verificate
      @verificate = Verificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verificate_params
      params.fetch(:verificate, {})
    end
end

app/helpers/verificates_helper.rb
module VerificatesHelper
end

app/views/verificates/_form.html.erb
<%= form_for(@verificate) do |f| %>
  <% if @verificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@verificate.errors.count, "error") %> prohibited this verificate from being saved:</h2>

      <ul>
      <% @verificate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/verificates/edit.html.erb
<h1>Editing Verificate</h1>

<%= render 'form' %>

<%= link_to 'Show', @verificate %> |
<%= link_to 'Back', verificates_path %>

app/views/verificates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Verificates</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verificates.each do |verificate| %>
      <tr>
        <td><%= link_to 'Show', verificate %></td>
        <td><%= link_to 'Edit', edit_verificate_path(verificate) %></td>
        <td><%= link_to 'Destroy', verificate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verificate', new_verificate_path %>

app/views/verificates/new.html.erb
<h1>New Verificate</h1>

<%= render 'form' %>

<%= link_to 'Back', verificates_path %>

app/views/verificates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_verificate_path(@verificate) %> |
<%= link_to 'Back', verificates_path %>