config/routes.rb
Rails.application.routes.draw do
  
  
  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :products
      resources :productos
      resources :verificates
    end
  end
end

app/models/producto.rb
class Producto < ActiveRecord::Base
end

app/controllers/api/v1/productos_controller.rb
class Api::V1::ProductosController < ApplicationController
  
  skip_before_action :verify_authenticity_token
  
  # GET /products
  def index
    productos = Producto.order("created_at DESC")
    render json: {status: 'Exitoso', message: 'Productos cargados', data: productos}, status: :ok
  end

  # GET /products/1
  def show
    productos = Producto.find(params[:id_producto])
    render json: {status: 'Exitoso', message: 'Productos cargados', data: producto}, status: :ok
  end
  
  def create
        producto = Producto.new(producto_params)
         
            if producto.save
                render json: {status: 'Exitoso', message: 'Producto creado', data: producto}, status: :ok
            else
                render json: {status: 'Error', message: 'No se grabo producto', data: producto.errors}, status: :unprocessable_entity
            end
        
    end
  
  
  private

    def producto_params
      params.permit(:id_producto, :descripcion_producto, :precio_producto, :stockCrear)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:id_producto, :descripcion_producto, :precio_producto, :stockCrear)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_producto %><br>
    <%= f.number_field :id_producto %>
  </div>
  <div class="field">
    <%= f.label :descripcion_producto %><br>
    <%= f.text_area :descripcion_producto %>
  </div>
  <div class="field">
    <%= f.label :precio_producto %><br>
    <%= f.text_field :precio_producto %>
  </div>
  <div class="field">
    <%= f.label :stockCrear %><br>
    <%= f.number_field :stockCrear %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Productos</h1>

<table>
  <thead>
    <tr>
      <th>Id producto</th>
      <th>Descripcion producto</th>
      <th>Precio producto</th>
      <th>Stockcrear</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.id_producto %></td>
        <td><%= producto.descripcion_producto %></td>
        <td><%= producto.precio_producto %></td>
        <td><%= producto.stockCrear %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id producto:</strong>
  <%= @producto.id_producto %>
</p>

<p>
  <strong>Descripcion producto:</strong>
  <%= @producto.descripcion_producto %>
</p>

<p>
  <strong>Precio producto:</strong>
  <%= @producto.precio_producto %>
</p>

<p>
  <strong>Stockcrear:</strong>
  <%= @producto.stockCrear %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>